name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  some-validation:
   runs-on: ubuntu-latest
   steps:
   - name: Some Checks
     run: |
          echo "Some valitation"
